apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-go-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WhatWR/devops-assignment
    targetRevision: HEAD
    path: kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-namespace-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
